MASTER         ?= $(notdir $(CURDIR)).pdf
LATEXMK        = latexmk $(LATEXMKFLAGS)
CLEANFLAGS     = -C

.PHONY: snippets wsdpdf clean FORCE_MAKE

$(MASTER) : wsdpdf FORCE_MAKE
	$(LATEXMK)

wsdpdf:
	../scripts/transform-wsd.sh pdf $(CURDIR)

clean:
	$(LATEXMK) $(CLEANFLAGS)
	rm -rf _minted-* *.appnote
	../scripts/transform-wsd.sh clean $(CURDIR)
